export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const ADD_RECIPE_DECK = 'ADD_RECIPE_DECK'
export const REMOVE_RECIPE_DECK = 'REMOVE_RECIPE_DECK'
export const COMPARE_RECIPES = 'COMPARE_RECIPES'

export const SAVE_RECIPE_DECK = "SAVE_RECIPE_DECK"
export const DELETE_RECIPE_DECK = "DELETE_RECIPE_DECK"

export const SELECT_CLUSTER = 'SELECT_CLUSTER'
export const UNSLELECT_CLUSTER = 'UNSELECT_CLUSTER'
