export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const ADD_RECIPE_DECK = 'ADD_RECIPE_DECK'
export const REMOVE_RECIPE_DECK = 'REMOVE_RECIPE_DECK'

export const SAVE_RECIPE_DECK = "SAVE_RECIPE_DECK"
export const DELETE_RECIPE_DECK = "DELETE_RECIPE_DECK"
export const LOAD_RECIPE_DECK = 'LOAD_RECIPE_DECK'

export const SELECT_RECIPE = 'SELECT_RECIPE'
export const COMPARE_RECIPES = 'COMPARE_RECIPES'
export const STOP_COMPARING = 'STOP_COMPARING'

export const SELECT_CLUSTER = 'SELECT_CLUSTER'
export const UNSELECT_CLUSTER = 'UNSELECT_CLUSTER'
